name = "phase-separation-integrated"
version = "0.1.3"
defaultTargets = ["ClassicalThermodynamics"]
[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.1"
[[lean_lib]]
name = "ClassicalThermodynamics"
