import ClassicalThermodynamics.Thermodynamics.Extensivity.Homogeneity
import Mathlib.Analysis.Calculus.FDeriv.Mul
import Mathlib.Analysis.Calculus.FDeriv.Prod
import Mathlib.Analysis.Calculus.Deriv.Inv
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Ring.RingNF

namespace ClassicalThermodynamics.Thermodynamics.Extensivity

noncomputable def densityState {ι : Type*} (volume : ℝ) (amount : ι → ℝ) : ι → ℝ :=
  fun i => amount i / volume

/-- Extensive free energy generated by a density free energy.

The zero-volume branch is defined as zero so that the construction is globally
one-homogeneous, including the scaling factor `0`. Derivative statements use
the nonzero-volume branch. -/
noncomputable def extensiveFreeEnergy {ι : Type*}
    (densityFreeEnergy : (ι → ℝ) → ℝ)
    (volume : ℝ) (amount : ι → ℝ) : ℝ :=
  if volume = 0 then 0 else volume * densityFreeEnergy (densityState volume amount)

theorem extensiveFreeEnergy_eq
    {ι : Type*} (densityFreeEnergy : (ι → ℝ) → ℝ)
    {volume : ℝ} (hvolume : volume ≠ 0) (amount : ι → ℝ) :
    extensiveFreeEnergy densityFreeEnergy volume amount =
      volume * densityFreeEnergy (densityState volume amount) := by
  simp [extensiveFreeEnergy, hvolume]

theorem extensiveFreeEnergy_oneHomogeneous
    {ι : Type*} (densityFreeEnergy : (ι → ℝ) → ℝ) :
    OneHomogeneous (fun x : ℝ × (ι → ℝ) =>
      extensiveFreeEnergy densityFreeEnergy x.1 x.2) := by
  intro scale hscale x
  rcases x with ⟨volume, amount⟩
  by_cases hzero : scale = 0
  · subst scale
    simp [extensiveFreeEnergy]
  by_cases hvolume : volume = 0
  · subst volume
    simp [extensiveFreeEnergy]
  have hscale_pos : 0 < scale := lt_of_le_of_ne hscale (Ne.symm hzero)
  have hscaledVolume : scale * volume ≠ 0 := mul_ne_zero hzero hvolume
  change extensiveFreeEnergy densityFreeEnergy (scale * volume)
      (fun i => scale * amount i) =
    scale * extensiveFreeEnergy densityFreeEnergy volume amount
  have hstate :
      densityState (scale * volume) (fun i => scale * amount i) =
        densityState volume amount := by
    funext i
    unfold densityState
    field_simp [hvolume, hzero]
  rw [extensiveFreeEnergy_eq _ hscaledVolume]
  rw [extensiveFreeEnergy_eq _ hvolume]
  rw [hstate]
  ring

theorem extensiveScalarFreeEnergy_oneHomogeneous
    (densityFreeEnergy : ℝ → ℝ) :
    OneHomogeneous (fun x : ℝ × ℝ =>
      if x.1 = 0 then 0 else x.1 * densityFreeEnergy (x.2 / x.1)) := by
  intro scale hscale x
  rcases x with ⟨volume, amount⟩
  by_cases hzero : scale = 0
  · subst scale
    simp
  by_cases hvolume : volume = 0
  · subst volume
    simp
  have hscaledVolume : scale * volume ≠ 0 := mul_ne_zero hzero hvolume
  simp only [smul_eq_mul, Prod.smul_mk]
  rw [if_neg hscaledVolume, if_neg hvolume]
  have hratio : (scale * amount) / (scale * volume) = amount / volume := by
    field_simp [hzero, hvolume]
  rw [hratio]
  ring

 theorem extensiveFreeEnergy_hasFDerivAt_of_product
    {ι : Type*} (densityFreeEnergy : (ι → ℝ) → ℝ)
    {volume : ℝ} (hvolume : volume ≠ 0) (amount : ι → ℝ)
    {F' : (ℝ × (ι → ℝ)) →L[ℝ] ℝ}
    (hproduct :
      HasFDerivAt
        (fun x : ℝ × (ι → ℝ) =>
          x.1 * densityFreeEnergy (densityState x.1 x.2))
        F' (volume, amount)) :
    HasFDerivAt
      (fun x : ℝ × (ι → ℝ) =>
        extensiveFreeEnergy densityFreeEnergy x.1 x.2)
      F' (volume, amount) := by
  apply hproduct.congr_of_eventuallyEq
  have hopen : IsOpen {x : ℝ × (ι → ℝ) | x.1 ≠ 0} :=
    isOpen_ne.preimage continuous_fst
  filter_upwards [hopen.mem_nhds (show (volume, amount) ∈
    {x : ℝ × (ι → ℝ) | x.1 ≠ 0} from hvolume)] with x hx
  simp [extensiveFreeEnergy, hx]

lemma densityState_hasFDerivAt_of_coordinate
    {ι : Type*} [Fintype ι]
    {volume : ℝ} (amount : ι → ℝ)
    (D : ∀ i, (ℝ × (ι → ℝ)) →L[ℝ] ℝ)
    (hcoord :
      ∀ i, HasFDerivAt
        (fun x : ℝ × (ι → ℝ) => densityState x.1 x.2 i)
        (D i) (volume, amount)) :
    HasFDerivAt
      (fun x : ℝ × (ι → ℝ) => densityState x.1 x.2)
      (ContinuousLinearMap.pi D) (volume, amount) :=
  (hasFDerivAt_pi).2 hcoord

lemma densityState_coordinate_hasFDerivAt
    {ι : Type*} [Fintype ι]
    {volume : ℝ} (hvolume : volume ≠ 0) (amount : ι → ℝ) (i : ι) :
    HasFDerivAt
      (fun x : ℝ × (ι → ℝ) => densityState x.1 x.2 i)
      ((-(amount i / volume ^ 2)) •
          ContinuousLinearMap.fst ℝ ℝ (ι → ℝ) +
        (volume⁻¹) •
          (ContinuousLinearMap.proj i).comp
            (ContinuousLinearMap.snd ℝ ℝ (ι → ℝ)))
      (volume, amount) := by
  have hnum :
      HasFDerivAt
        (fun x : ℝ × (ι → ℝ) => x.2 i)
        ((ContinuousLinearMap.proj i).comp
          (ContinuousLinearMap.snd ℝ ℝ (ι → ℝ)))
        (volume, amount) := by
    exact (hasFDerivAt_apply i amount).comp
      (volume, amount) (hasFDerivAt_snd (𝕜 := ℝ))
  have hden :
      HasFDerivAt
        (fun x : ℝ × (ι → ℝ) => x.1)
        (ContinuousLinearMap.fst ℝ ℝ (ι → ℝ))
        (volume, amount) :=
    hasFDerivAt_fst (𝕜 := ℝ)
  have hinv := (hasFDerivAt_inv hvolume).comp
    (volume, amount) hden
  have hquot := hnum.mul hinv
  convert hquot using 1
  · funext x
    simp [densityState, div_eq_mul_inv, Function.comp_def, mul_comm]
  · apply ContinuousLinearMap.ext
    intro z
    rcases z with ⟨dv, dN⟩
    simp
    ring

lemma densityState_hasFDerivAt
    {ι : Type*} [Fintype ι]
    {volume : ℝ} (hvolume : volume ≠ 0) (amount : ι → ℝ) :
    HasFDerivAt
      (fun x : ℝ × (ι → ℝ) => densityState x.1 x.2)
      (ContinuousLinearMap.pi (fun i =>
        (-(amount i / volume ^ 2)) •
            ContinuousLinearMap.fst ℝ ℝ (ι → ℝ) +
          (volume⁻¹) •
            (ContinuousLinearMap.proj i).comp
              (ContinuousLinearMap.snd ℝ ℝ (ι → ℝ))))
      (volume, amount) :=
  densityState_hasFDerivAt_of_coordinate amount _ fun i =>
    densityState_coordinate_hasFDerivAt hvolume amount i

/-- Transfer a finite-component density free-energy derivative through
the quotient composition `N / V`. This is the reusable entry point for
model-specific extensive adapters. -/
lemma densityFreeEnergy_densityState_hasFDerivAt
    {ι : Type*} [Fintype ι]
    (densityFreeEnergy : (ι → ℝ) → ℝ)
    {volume : ℝ} (hvolume : volume ≠ 0) (amount : ι → ℝ)
    {D : (ι → ℝ) →L[ℝ] ℝ}
    (hfree :
      HasFDerivAt densityFreeEnergy D (densityState volume amount)) :
    HasFDerivAt
      (fun x : ℝ × (ι → ℝ) =>
        densityFreeEnergy (densityState x.1 x.2))
      (D.comp (ContinuousLinearMap.pi (fun i =>
        (-(amount i / volume ^ 2)) •
            ContinuousLinearMap.fst ℝ ℝ (ι → ℝ) +
          (volume⁻¹) •
            (ContinuousLinearMap.proj i).comp
              (ContinuousLinearMap.snd ℝ ℝ (ι → ℝ)))))
      (volume, amount) := by
  exact hfree.comp (volume, amount)
    (densityState_hasFDerivAt hvolume amount)

theorem extensiveFreeEnergy_binary_hasFDerivAt_of_product
    (densityFreeEnergy : (Fin 2 → ℝ) → ℝ)
    {volume : ℝ} (hvolume : volume ≠ 0) (amount : Fin 2 → ℝ)
    {F' : (ℝ × (Fin 2 → ℝ)) →L[ℝ] ℝ}
    (hproduct :
      HasFDerivAt
        (fun x : ℝ × (Fin 2 → ℝ) =>
          x.1 * densityFreeEnergy (densityState x.1 x.2))
        F' (volume, amount)) :
    HasFDerivAt
      (fun x : ℝ × (Fin 2 → ℝ) =>
        extensiveFreeEnergy densityFreeEnergy x.1 x.2)
      F' (volume, amount) :=
  extensiveFreeEnergy_hasFDerivAt_of_product
    densityFreeEnergy hvolume amount hproduct

theorem extensiveScalarFreeEnergy_hasFDerivAt_of_product
    (densityFreeEnergy : ℝ → ℝ)
    {volume amount : ℝ} (hvolume : volume ≠ 0)
    {F' : (ℝ × ℝ) →L[ℝ] ℝ}
    (hproduct :
      HasFDerivAt
        (fun x : ℝ × ℝ =>
          x.1 * densityFreeEnergy (x.2 / x.1))
        F' (volume, amount)) :
    HasFDerivAt
      (fun x : ℝ × ℝ =>
        if x.1 = 0 then 0 else x.1 * densityFreeEnergy (x.2 / x.1))
      F' (volume, amount) := by
  apply hproduct.congr_of_eventuallyEq
  have hopen : IsOpen {x : ℝ × ℝ | x.1 ≠ 0} :=
    isOpen_ne.preimage continuous_fst
  filter_upwards [hopen.mem_nhds (show (volume, amount) ∈
    {x : ℝ × ℝ | x.1 ≠ 0} from hvolume)] with x hx
  simp [hx]

theorem extensiveScalarFreeEnergy_hasFDerivAt_of_densityComposition
    (densityFreeEnergy : ℝ → ℝ)
    {volume amount : ℝ} (hvolume : volume ≠ 0)
    {G : (ℝ × ℝ) →L[ℝ] ℝ}
    (hcomposition :
      HasFDerivAt
        (fun x : ℝ × ℝ =>
          densityFreeEnergy (x.2 / x.1))
        G (volume, amount))
    (hvolumeDerivative :
      HasFDerivAt (fun x : ℝ × ℝ => x.1)
        (ContinuousLinearMap.fst ℝ ℝ ℝ) (volume, amount)) :
    HasFDerivAt
      (fun x : ℝ × ℝ =>
        if x.1 = 0 then 0 else x.1 * densityFreeEnergy (x.2 / x.1))
      (volume • G +
        densityFreeEnergy (amount / volume) •
          ContinuousLinearMap.fst ℝ ℝ ℝ)
      (volume, amount) := by
  have hproduct :
      HasFDerivAt
        (fun x : ℝ × ℝ =>
          x.1 * densityFreeEnergy (x.2 / x.1))
        (volume • G +
          densityFreeEnergy (amount / volume) •
            ContinuousLinearMap.fst ℝ ℝ ℝ)
        (volume, amount) := by
    convert hvolumeDerivative.mul hcomposition using 1 <;>
      simp [Function.comp_def, div_eq_mul_inv, mul_comm, mul_left_comm,
        mul_assoc]
  exact extensiveScalarFreeEnergy_hasFDerivAt_of_product
    densityFreeEnergy hvolume hproduct

lemma scalarDensity_hasFDerivAt
    {volume amount : ℝ} (hvolume : volume ≠ 0) :
    HasFDerivAt
      (fun x : ℝ × ℝ => x.2 / x.1)
      ((-(amount / volume ^ 2)) • ContinuousLinearMap.fst ℝ ℝ ℝ +
        (volume⁻¹) • ContinuousLinearMap.snd ℝ ℝ ℝ)
      (volume, amount) := by
  have hnum :
      HasFDerivAt (fun x : ℝ × ℝ => x.2)
        (ContinuousLinearMap.snd ℝ ℝ ℝ) (volume, amount) :=
    hasFDerivAt_snd (𝕜 := ℝ)
  have hden :
      HasFDerivAt (fun x : ℝ × ℝ => x.1)
        (ContinuousLinearMap.fst ℝ ℝ ℝ) (volume, amount) :=
    hasFDerivAt_fst (𝕜 := ℝ)
  have hinv := (hasFDerivAt_inv hvolume).comp
    (volume, amount) hden
  have hquot := hnum.mul hinv
  convert hquot using 1
  · funext x
    simp [div_eq_mul_inv, Function.comp_def, mul_comm]
  · apply ContinuousLinearMap.ext
    intro z
    rcases z with ⟨dv, da⟩
    simp
    ring

/-- Construct the extensive derivative from a finite-component density
free-energy derivative. The theorem is derivative-certified; it does not
assert that a model's canonical chemical-potential formula is derived. -/
theorem extensiveFreeEnergy_hasFDerivAt_of_densityDerivative
    {ι : Type*} [Fintype ι]
    (densityFreeEnergy : (ι → ℝ) → ℝ)
    {volume : ℝ} (hvolume : volume ≠ 0) (amount : ι → ℝ)
    {D : (ι → ℝ) →L[ℝ] ℝ}
    (hfree :
      HasFDerivAt densityFreeEnergy D (densityState volume amount)) :
    HasFDerivAt
      (fun x : ℝ × (ι → ℝ) =>
        extensiveFreeEnergy densityFreeEnergy x.1 x.2)
      (volume •
          (D.comp (ContinuousLinearMap.pi (fun i =>
            (-(amount i / volume ^ 2)) •
                ContinuousLinearMap.fst ℝ ℝ (ι → ℝ) +
              (volume⁻¹) •
                (ContinuousLinearMap.proj i).comp
                  (ContinuousLinearMap.snd ℝ ℝ (ι → ℝ))))) +
        densityFreeEnergy (densityState volume amount) •
          ContinuousLinearMap.fst ℝ ℝ (ι → ℝ))
      (volume, amount) := by
  have hcomposition :=
    densityFreeEnergy_densityState_hasFDerivAt
      densityFreeEnergy hvolume amount hfree
  have hproduct :
      HasFDerivAt
        (fun x : ℝ × (ι → ℝ) =>
          x.1 * densityFreeEnergy (densityState x.1 x.2))
        (volume •
            (D.comp (ContinuousLinearMap.pi (fun i =>
              (-(amount i / volume ^ 2)) •
                  ContinuousLinearMap.fst ℝ ℝ (ι → ℝ) +
                (volume⁻¹) •
                  (ContinuousLinearMap.proj i).comp
                    (ContinuousLinearMap.snd ℝ ℝ (ι → ℝ))))) +
          densityFreeEnergy (densityState volume amount) •
            ContinuousLinearMap.fst ℝ ℝ (ι → ℝ))
        (volume, amount) := by
    convert (hasFDerivAt_fst (𝕜 := ℝ)).mul hcomposition using 1
  exact extensiveFreeEnergy_hasFDerivAt_of_product
    densityFreeEnergy hvolume amount hproduct

end ClassicalThermodynamics.Thermodynamics.Extensivity
